# Generated by Django 5.0.2 on 2024-02-21 13:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("company", "0002_eployee_team"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="team",
            name="id",
        ),
        migrations.AlterField(
            model_name="team",
            name="name",
            field=models.CharField(max_length=15, primary_key=True, serialize=False),
        ),
    ]
