# Generated by Django 5.0.2 on 2024-02-21 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("company", "0003_remove_team_id_alter_team_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="manger",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="company.eployee",
            ),
        ),
    ]
