# Generated by Django 5.0.2 on 2024-02-21 15:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("company", "0007_alter_teamleader_manger"),
    ]

    operations = [
        migrations.AlterField(
            model_name="epmloyee",
            name="team",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="company.epmloyee",
            ),
        ),
    ]
