# Generated by Django 5.0.2 on 2024-02-21 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("company", "0008_alter_epmloyee_team"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="teamleader",
            name="manger",
        ),
        migrations.AlterField(
            model_name="epmloyee",
            name="team",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="company.teamleader"
            ),
        ),
    ]
